export const CHROME_OPTIONS_UPDATE_STATE = 'CHROME_OPTIONS_UPDATE_STATE';

export const TABS_UPDATE_TABS_PER_WINDOW_BY = 'TABS_UPDATE_TABS_PER_WINDOW_BY';
export const TABS_UPDATE_TABS_PER_WINDOW = 'TABS_UPDATE_TABS_PER_WINDOW';

export const RULES_MOVE_TO_PREVIOUS = 'RULES_MOVE_TO_PREVIOUS';
export const RULES_MOVE_TO_NEXT = 'RULES_MOVE_TO_NEXT';
export const RULES_MOVE_TO_GROUP_BY_ID = 'RULES_MOVE_TO_GROUP_BY_ID';
export const RULES_MODIFY_REGEXP_BY_ID = 'RULES_MODIFY_REGEXP_BY_ID';
export const RULES_TOGGLE_DISABLE_BY_ID = 'RULES_TOGGLE_DISABLE_BY_ID';
export const RULES_TOGGLE_ISOLATE_BY_ID = 'RULES_TOGGLE_ISOLATE_BY_ID';
export const RULES_ADD = 'RULES_ADD';
export const RULES_REMOVE_BY_ID = 'RULES_REMOVE_BY_ID';
