export const CHROME_OPTIONS_UPDATE_STATE = 'CHROME_OPTIONS_UPDATE_STATE';

export const TABS_UPDATE_TABS_PER_WINDOW_BY = 'TABS_UPDATE_TABS_PER_WINDOW_BY';
export const TABS_UPDATE_TABS_PER_WINDOW = 'TABS_UPDATE_TABS_PER_WINDOW';
