import keyMirror from 'key-mirror';

const keys = keyMirror({
  CHROME_OPTIONS_UPDATE_STATE: null,

  OPTIONS_LOAD_START_WITH_STATE: null,
  OPTIONS_LOAD_START: null,
  OPTIONS_LOAD_SUCCESS: null,
  OPTIONS_LOAD_FAILURE: null,
  OPTIONS_SAVE_START: null,
  OPTIONS_SAVE_SUCCESS: null,
  OPTIONS_SAVE_FAILURE: null,
  OPTIONS_UPDATE_STATE: null,
  OPTIONS_SERIALIZE: null,
  OPTIONS_DESERIALIZE_FAILURE: null,
  OPTIONS_UPDATE_SERIALIZED_STATE: null,

  TABS_UPDATE_TABS_PER_WINDOW_BY: null,
  TABS_UPDATE_TABS_PER_WINDOW: null,

  RULES_MOVE_TO_PREVIOUS: null,
  RULES_MOVE_TO_NEXT: null,
  RULES_MOVE_TO_GROUP_BY_ID: null,
  RULES_MODIFY_REGEXP_BY_ID: null,
  RULES_TOGGLE_DISABLE_BY_ID: null,
  RULES_TOGGLE_ISOLATE_BY_ID: null,
  RULES_ADD: null,
  RULES_REMOVE_BY_ID: null
});

module.exports = keys;
module.exports.default = keys;
