// React DnD
export DND_ITEM_TYPE_RULE = 'DND_ITEM_TYPE_RULE';

export const RULES_MOVE_TO_PREVIOUS = 'RULES_MOVE_TO_PREVIOUS';
export const RULES_MOVE_TO_NEXT = 'RULES_MOVE_TO_NEXT';
export const RULES_MOVE_TO_GROUP_BY_ID = 'RULES_MOVE_TO_GROUP_BY_ID';
export const RULES_MODIFY_REGEXP_BY_ID = 'RULES_MODIFY_REGEXP_BY_ID';
export const RULES_TOGGLE_DISABLE_BY_ID = 'RULES_TOGGLE_DISABLE_BY_ID';
export const RULES_TOGGLE_ISOLATE_BY_ID = 'RULES_TOGGLE_ISOLATE_BY_ID';
export const RULES_ADD = 'RULES_ADD';
export const RULES_REMOVE_BY_ID = 'RULES_REMOVE_BY_ID';
